In [8]:
# load packages
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [9]:
# load application dataset
applications = pd.read_csv("../datasets/raw/applications.csv")

# initial inspection
display(applications.info(), applications.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30005 entries, 0 to 30004
Columns: 181 entries, id to prev_nflag_insured_on_approval_avg
dtypes: bool(2), float64(124), int64(41), object(14)
memory usage: 41.0+ MB

None

,id,target,name_contract_type,code_gender,flag_own_car,flag_own_realty,cnt_children,amt_income_total,amt_credit,amt_annuity,amt_goods_price,name_type_suite,name_income_type,name_education_type,name_family_status,name_housing_type,region_population_relative,age,days_employed,days_registration,days_id_publish,own_car_age,flag_mobil,flag_emp_phone,flag_work_phone,flag_cont_mobile,flag_phone,flag_email,occupation_type,cnt_fam_members,region_rating_client,region_rating_client_w_city,weekday_appr_process_start,hour_appr_process_start,reg_region_not_live_region,reg_region_not_work_region,live_region_not_work_region,reg_city_not_live_city,reg_city_not_work_city,live_city_not_work_city,organization_type,ext_source_1,ext_source_2,ext_source_3,apartments_avg,basementarea_avg,years_beginexpluatation_avg,years_build_avg,commonarea_avg,elevators_avg,entrances_avg,floorsmax_avg,floorsmin_avg,landarea_avg,livingapartments_avg,livingarea_avg,nonlivingapartments_avg,nonlivingarea_avg,apartments_mode,basementarea_mode,years_beginexpluatation_mode,years_build_mode,commonarea_mode,elevators_mode,entrances_mode,floorsmax_mode,floorsmin_mode,landarea_mode,livingapartments_mode,livingarea_mode,nonlivingapartments_mode,nonlivingarea_mode,apartments_medi,basementarea_medi,years_beginexpluatation_medi,years_build_medi,commonarea_medi,elevators_medi,entrances_medi,floorsmax_medi,floorsmin_medi,landarea_medi,livingapartments_medi,livingarea_medi,nonlivingapartments_medi,nonlivingarea_medi,fondkapremont_mode,housetype_mode,totalarea_mode,wallsmaterial_mode,emergencystate_mode,obs_30_cnt_social_circle,def_30_cnt_social_circle,obs_60_cnt_social_circle,def_60_cnt_social_circle,days_last_phone_change,flag_document_2,flag_document_3,flag_document_4,flag_document_5,flag_document_6,flag_document_7,flag_document_8,flag_document_9,flag_document_10,flag_document_11,flag_document_12,flag_document_13,flag_document_14,flag_document_15,flag_document_16,flag_document_17,flag_document_18,flag_document_19,flag_document_20,flag_document_21,amt_req_credit_bureau_hour,amt_req_credit_bureau_day,amt_req_credit_bureau_week,amt_req_credit_bureau_mon,amt_req_credit_bureau_qrt,amt_req_credit_bureau_year,sk_id_prev_count,cnt_instalment_future_sum,sk_dpd_max,sk_dpd_sum,sk_dpd_def_max,sk_dpd_def_sum,sk_id_bureau_count,credit_day_overdue_sum,cnt_credit_prolong_avg,amt_credit_sum_sum,amt_credit_sum_debt_sum,amt_credit_sum_limit_sum,amt_credit_sum_overdue_sum,amt_annuity_sum,active_sum,amt_balance_avg_avg,amt_drawings_atm_current_avg_avg,amt_drawings_current_avg_avg,amt_drawings_other_current_avg_avg,amt_drawings_pos_current_avg_avg,amt_inst_min_regularity_avg_avg,amt_payment_current_avg_avg,amt_payment_total_current_avg_avg,amt_receivable_principal_avg_avg,amt_recivable_avg_avg,amt_total_receivable_avg_avg,cnt_drawings_atm_current_avg_avg,cnt_drawings_current_avg_avg,cnt_drawings_other_current_avg_avg,cnt_drawings_pos_current_avg_avg,cnt_instalment_mature_cum_avg_avg,sk_dpd_avg_avg,sk_dpd_def_avg_avg,negative_balance_avg_avg,negative_balance_sum_sum,count,installment_paiement_delay_min_min,installment_paiement_delay_max_max,installment_paiement_delay_avg_avg,amount_instalment_difference_min_min,amount_instalment_difference_max_max,amount_instalment_difference_avg_avg,prev_amt_annuity_sum,prev_amt_application_sum,prev_amt_credit_sum,prev_amt_down_payment_sum,prev_amt_goods_price_sum,prev_rate_down_payment_avg,prev_rate_interest_primary_avg,prev_rate_interest_privileged_avg,prev_days_decision_avg,prev_name_payment_type_count,prev_cnt_payment_sum,prev_days_first_drawing_avg,prev_days_first_due_avg,prev_days_last_due_1st_version_avg,prev_days_last_due_avg,prev_days_termination_avg,prev_nflag_insured_on_approval_avg
0,100599,0,Cash loans,M,False,True,0,315000.0,835380.0,40320.0,675000.0,"Spouse, partner",Commercial associate,Secondary / secondary special,Married,House / apartment,0.032561,44,3820,8386.0,4028,NaN,1,1,0,1,0,0,Laborers,2.0,1,1,FRIDAY,12,0,0,0,0,0,0,Business Entity Type 1,NaN,0.682405,0.053478,0.0742,0.0581,0.9767,0.6804,0.0,0.0,0.2414,0.1667,0.2083,0.0601,0.0588,0.0667,0.0077,0.0061,0.0756,0.0603,0.9767,0.6929,0.0,0.0,0.2414,0.1667,0.2083,0.0615,0.0643,0.0694,0.0078,0.0065,0.0749,0.0581,0.9767,0.6847,0.0,0.0,0.2414,0.1667,0.2083,0.0612,0.0599,0.0679,0.0078,0.0062,reg oper account,block of flats,0.0535,Panel,False,0.0,0.0,0.0,0.0,-671.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,11.0,315.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,1415853.0,1244713.5,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-4.0,30.0,6.916667,0.0,31188.96,5571.645000,33429.870,630000.0,694863.0,NaN,630000.0,NaN,NaN,NaN,671.00,1.0,36.0,365243.0,-638.0,412.0,-368.000000,-362.000000,0.000000
1,165926,0,Cash loans,F,False,True,2,157500.0,163008.0,17424.0,144000.0,Unaccompanied,Commercial associate,Secondary / secondary special,Married,With parents,0.006629,39,1304,4717.0,3486,NaN,1,1,0,1,0,0,Sales staff,4.0,2,2,THURSDAY,6,0,0,0,1,1,0,Self-employed,NaN,0.296449,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-2.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0,24.0,142.0,1.0,2.0,1.0,2.0,2.0,0.0,0.0,450738.0,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-10.0,33.0,7.624242,0.0,19414.89,1960.744500,75930.255,270000.0,1093959.0,NaN,270000.0,NaN,NaN,NaN,522.00,3.0,24.0,365243.0,-557.5,-227.5,-242.500000,-235.000000,1.000000
2,192297,0,Cash loans,F,False,True,0,157500.0,1006920.0,42790.5,900000.0,Unaccompanied,Pensioner,Lower secondary,Married,House / apartment,0.018850,52,-365243,3924.0,2465,NaN,1,0,0,1,0,0,NaN,2.0,2,2,TUESDAY,10,0,0,0,0,0,0,XNA,0.459448,0.855000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,0.0,3.0,0.0,-508.0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,13.0,78.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,27.0,18.333333,0.0,0.00,0.000000,20975.040,206959.5,224716.5,0.0,206959.5,0.00000,NaN,NaN,508.00,1.0,12.0,365243.0,-476.0,-146.0,-146.000000,-142.000000,0.000000
3,127408,0,Cash loans,M,True,False,1,130500.0,835605.0,24561.0,697500.0,Unaccompanied,Working,Higher education,Civil marriage,House / apartment,0.031329,39,275,3782.0,4349,64.0,1,1,0,1,0,0,Laborers,3.0,2,2,THURSDAY,7,0,0,0,0,1,1,Trade: type 7,0.483715,0.025700,0.382502,0.1031,NaN,0.9836,0.7756,NaN,0.0,0.2069,0.1667,0.2083,0.0415,NaN,0.0877,NaN,0.0070,0.1050,NaN,0.9836,0.7844,NaN,0.0,0.2069,0.1667,0.2083,0.0424,NaN,0.0914,NaN,0.0074,0.1041,NaN,0.9836,0.7786,NaN,0.0,0.2069,0.1667,0.2083,0.0422,NaN,0.0893,NaN,0.0071,reg oper account,block of flats,0.0706,Block,False,1.0,0.0,1.0,0.0,-207.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,13.0,68.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,135000.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-6.0,31.0,15.884615,0.0,3028.32,375.805385,31331.970,1019371.5,1017954.0,5400.0,1019371.5,0.05927,NaN,NaN,587.00,3.0,72.0,365243.0,-1510.0,-1180.0,-1210.000000,-1201.000000,0.000000
4,118673,0,Cash loans,F,False,True,0,202500.0,152820.0,16047.0,135000.0,Unaccompanied,Working,Secondary / secondary special,Civil marriage,House / apartment,0.002506,48,2192,7013.0,1052,NaN,1,1,0,1,0,0,Laborers,2.0,2,2,MONDAY,8,0,0,0,0,1,1,Business Entity Type 3,NaN,0.236240,0.780144,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,0.0,0.0,0.0,0.0,-611.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0,16.0,77.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,238500.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,38.0,24.250000,0.0,0.00,0.000000,34127.955,223114.5,248283.0,0.0,223114.5,0.00000,NaN,NaN,284.75,4.0,24.0,365243.0,-301.0,-91.0,121564.666667,121567.333333,0.333333

In [10]:
# check column names
applications.columns

Index(['id', 'target', 'name_contract_type', 'code_gender', 'flag_own_car',
       'flag_own_realty', 'cnt_children', 'amt_income_total', 'amt_credit',
       'amt_annuity',
       ...
       'prev_rate_interest_privileged_avg', 'prev_days_decision_avg',
       'prev_name_payment_type_count', 'prev_cnt_payment_sum',
       'prev_days_first_drawing_avg', 'prev_days_first_due_avg',
       'prev_days_last_due_1st_version_avg', 'prev_days_last_due_avg',
       'prev_days_termination_avg', 'prev_nflag_insured_on_approval_avg'],
      dtype='object', length=181)

In [11]:
count_missing = applications.isna().sum()
perc_missing = applications.isna().sum() * 100 / len(applications)

perc_missing_df = pd.DataFrame({
    "col_name": applications.columns,
    "count_missing":count_missing,
    "percent_missing": perc_missing
    })

perc_missing_df.sort_values(by="percent_missing", ascending=True, ignore_index=True, inplace=True)

perc_missing_df

                                 col_name  count_missing  percent_missing
0                                      id              0         0.000000
1                 hour_appr_process_start              0         0.000000
2              reg_region_not_live_region              0         0.000000
3              reg_region_not_work_region              0         0.000000
4             live_region_not_work_region              0         0.000000
5                  reg_city_not_live_city              0         0.000000
6                         flag_document_2              0         0.000000
7                 live_city_not_work_city              0         0.000000
8                       organization_type              0         0.000000
9                        flag_document_21              0         0.000000
10                       flag_document_20              0         0.000000
11                       flag_document_19              0         0.000000
12                       flag_document_18              0         0.000000
13                       flag_document_17              0         0.000000
14                       flag_document_16              0         0.000000
15                       flag_document_15              0         0.000000
16                       flag_document_14              0         0.000000
17                       flag_document_13              0         0.000000
18                       flag_document_12              0         0.000000
19                       flag_document_11              0         0.000000
20                       flag_document_10              0         0.000000
21                        flag_document_9              0         0.000000
22                        flag_document_8              0         0.000000
23                        flag_document_7              0         0.000000
24                        flag_document_6              0         0.000000
25                        flag_document_5              0         0.000000
26                        flag_document_4              0         0.000000
27                        flag_document_3              0         0.000000
28             weekday_appr_process_start              0         0.000000
29            region_rating_client_w_city              0         0.000000
30                 reg_city_not_work_city              0         0.000000
31                 days_last_phone_change              0         0.000000
32                   region_rating_client              0         0.000000
33                                    age              0         0.000000
34             region_population_relative              0         0.000000
35                      name_housing_type              0         0.000000
36                     name_family_status              0         0.000000
37                    name_education_type              0         0.000000
38                       name_income_type              0         0.000000
39                             amt_credit              0         0.000000
40                       amt_income_total              0         0.000000
41                           cnt_children              0         0.000000
42                          days_employed              0         0.000000
43                        flag_own_realty              0         0.000000
44                            code_gender              0         0.000000
45                        days_id_publish              0         0.000000
46                     name_contract_type              0         0.000000
47                             flag_mobil              0         0.000000
48                         flag_emp_phone              0         0.000000
49                        flag_work_phone              0         0.000000
50                       flag_cont_mobile              0         0.000000
51                             flag_phone              0         0.000000
52                             flag_email              0         0.000000
53                                 target              0         0.000000
54                           flag_own_car              0         0.000000
55                      days_registration              0         0.000000
56                            amt_annuity              1         0.003333
57                        cnt_fam_members              1         0.003333
58                        amt_goods_price             29         0.096651
59                           ext_source_2             66         0.219963
60               obs_60_cnt_social_circle            107         0.356607
61               def_30_cnt_social_circle            107         0.356607
62               obs_30_cnt_social_circle            107         0.356607
63               def_60_cnt_social_circle            107         0.356607
64                        name_type_suite            138         0.459923
65     installment_paiement_delay_max_max           1574         5.245792
66     installment_paiement_delay_min_min           1574         5.245792
67     installment_paiement_delay_avg_avg           1574         5.245792
68   amount_instalment_difference_avg_avg           1574         5.245792
69   amount_instalment_difference_max_max           1574         5.245792
70   amount_instalment_difference_min_min           1574         5.245792
71                 prev_days_decision_avg           1627         5.422430
72           prev_name_payment_type_count           1627         5.422430
73               prev_amt_application_sum           1627         5.422430
74                    prev_amt_credit_sum           1627         5.422430
75                   prev_cnt_payment_sum           1672         5.572405
76                   prev_amt_annuity_sum           1672         5.572405
77               prev_amt_goods_price_sum           1719         5.729045
78                prev_days_first_due_avg           1754         5.845692
79     prev_days_last_due_1st_version_avg           1754         5.845692
80                 prev_days_last_due_avg           1754         5.845692
81            prev_days_first_drawing_avg           1754         5.845692
82              prev_days_termination_avg           1754         5.845692
83     prev_nflag_insured_on_approval_avg           1754         5.845692
84                       sk_id_prev_count           1787         5.955674
85                             sk_dpd_max           1787         5.955674
86                             sk_dpd_sum           1787         5.955674
87                         sk_dpd_def_sum           1787         5.955674
88                         sk_dpd_def_max           1787         5.955674
89              cnt_instalment_future_sum           1788         5.959007
90             prev_rate_down_payment_avg           3384        11.278120
91              prev_amt_down_payment_sum           3384        11.278120
92             amt_req_credit_bureau_hour           4007        13.354441
93             amt_req_credit_bureau_week           4007        13.354441
94              amt_req_credit_bureau_mon           4007        13.354441
95              amt_req_credit_bureau_qrt           4007        13.354441
96             amt_req_credit_bureau_year           4007        13.354441
97              amt_req_credit_bureau_day           4007        13.354441
98                     sk_id_bureau_count           4249        14.160973
99                 cnt_credit_prolong_avg           4249        14.160973
100                    amt_credit_sum_sum           4249        14.160973
101            amt_credit_sum_overdue_sum           4249        14.160973
102                            active_sum           4249        14.160973
103                credit_day_overdue_sum           4249        14.160973
104               amt_credit_sum_debt_sum           4951        16.500583
105                          ext_source_3           5914        19.710048
106              amt_credit_sum_limit_sum           6282        20.936511
107                       occupation_type           9476        31.581403
108                   emergencystate_mode          14291        47.628729
109                        totalarea_mode          14569        48.555241
110          years_beginexpluatation_medi          14735        49.108482
111          years_beginexpluatation_mode          14735        49.108482
112           years_beginexpluatation_avg          14735        49.108482
113                        floorsmax_medi          15022        50.064989
114                         floorsmax_avg          15022        50.064989
115                        floorsmax_mode          15022        50.064989
116                        housetype_mode          15153        50.501583
117                        livingarea_avg          15209        50.688219
118                       livingarea_mode          15209        50.688219
119                       livingarea_medi          15209        50.688219
120                        entrances_mode          15216        50.711548
121                         entrances_avg          15216        50.711548
122                        entrances_medi          15216        50.711548
123                       apartments_mode          15319        51.054824
124                        apartments_avg          15319        51.054824
125                       apartments_medi          15319        51.054824
126                    wallsmaterial_mode          15364        51.204799
127                         elevators_avg          16097        53.647725
128                        elevators_mode          16097        53.647725
129                        elevators_medi          16097        53.647725
130                     nonlivingarea_avg          16667        55.547409
131                    nonlivingarea_mode          16667        55.547409
132                    nonlivingarea_medi          16667        55.547409
133                          ext_source_1          16850        56.157307
134                     basementarea_mode          17703        59.000167
135                     basementarea_medi          17703        59.000167
136                      basementarea_avg          17703        59.000167
137                          landarea_avg          17967        59.880020
138                         landarea_mode          17967        59.880020
139                         landarea_medi          17967        59.880020
140                           own_car_age          19816        66.042326
141                       years_build_avg          20048        66.815531
142                      years_build_mode          20048        66.815531
143                      years_build_medi          20048        66.815531
144                        floorsmin_mode          20463        68.198634
145                        floorsmin_medi          20463        68.198634
146                         floorsmin_avg          20463        68.198634
147                    fondkapremont_mode          20566        68.541910
148                 livingapartments_mode          20618        68.715214
149                 livingapartments_medi          20618        68.715214
150                  livingapartments_avg          20618        68.715214
151               nonlivingapartments_avg          20941        69.791701
152              nonlivingapartments_medi          20941        69.791701
153              nonlivingapartments_mode          20941        69.791701
154                        commonarea_avg          21050        70.154974
155                       commonarea_mode          21050        70.154974
156                       commonarea_medi          21050        70.154974
157                   amt_balance_avg_avg          21579        71.918014
158          amt_drawings_current_avg_avg          21579        71.918014
159       amt_inst_min_regularity_avg_avg          21579        71.918014
160     cnt_instalment_mature_cum_avg_avg          21579        71.918014
161      amt_receivable_principal_avg_avg          21579        71.918014
162                 amt_recivable_avg_avg          21579        71.918014
163                        sk_dpd_avg_avg          21579        71.918014
164     amt_payment_total_current_avg_avg          21579        71.918014
165                    sk_dpd_def_avg_avg          21579        71.918014
166          cnt_drawings_current_avg_avg          21579        71.918014
167              negative_balance_avg_avg          21579        71.918014
168              negative_balance_sum_sum          21579        71.918014
169                                 count          21579        71.918014
170          amt_total_receivable_avg_avg          21579        71.918014
171                       amt_annuity_sum          22155        73.837694
172      amt_drawings_atm_current_avg_avg          24097        80.309948
173      cnt_drawings_atm_current_avg_avg          24097        80.309948
174    amt_drawings_other_current_avg_avg          24097        80.309948
175      amt_drawings_pos_current_avg_avg          24097        80.309948
176    cnt_drawings_other_current_avg_avg          24097        80.309948
177      cnt_drawings_pos_current_avg_avg          24097        80.309948
178           amt_payment_current_avg_avg          24107        80.343276
179        prev_rate_interest_primary_avg          29547        98.473588
180     prev_rate_interest_privileged_avg          29547        98.473588

In [12]:
# rename column
applications = applications.rename(columns={"target":"credit_event"})

# remove sensitive variables
applications = applications.drop(columns=["code_gender", "age", "name_family_status"])

# display results
display(applications.shape, applications.head())

(30005, 178)

,id,credit_event,name_contract_type,flag_own_car,flag_own_realty,cnt_children,amt_income_total,amt_credit,amt_annuity,amt_goods_price,name_type_suite,name_income_type,name_education_type,name_housing_type,region_population_relative,days_employed,days_registration,days_id_publish,own_car_age,flag_mobil,flag_emp_phone,flag_work_phone,flag_cont_mobile,flag_phone,flag_email,occupation_type,cnt_fam_members,region_rating_client,region_rating_client_w_city,weekday_appr_process_start,hour_appr_process_start,reg_region_not_live_region,reg_region_not_work_region,live_region_not_work_region,reg_city_not_live_city,reg_city_not_work_city,live_city_not_work_city,organization_type,ext_source_1,ext_source_2,ext_source_3,apartments_avg,basementarea_avg,years_beginexpluatation_avg,years_build_avg,commonarea_avg,elevators_avg,entrances_avg,floorsmax_avg,floorsmin_avg,landarea_avg,livingapartments_avg,livingarea_avg,nonlivingapartments_avg,nonlivingarea_avg,apartments_mode,basementarea_mode,years_beginexpluatation_mode,years_build_mode,commonarea_mode,elevators_mode,entrances_mode,floorsmax_mode,floorsmin_mode,landarea_mode,livingapartments_mode,livingarea_mode,nonlivingapartments_mode,nonlivingarea_mode,apartments_medi,basementarea_medi,years_beginexpluatation_medi,years_build_medi,commonarea_medi,elevators_medi,entrances_medi,floorsmax_medi,floorsmin_medi,landarea_medi,livingapartments_medi,livingarea_medi,nonlivingapartments_medi,nonlivingarea_medi,fondkapremont_mode,housetype_mode,totalarea_mode,wallsmaterial_mode,emergencystate_mode,obs_30_cnt_social_circle,def_30_cnt_social_circle,obs_60_cnt_social_circle,def_60_cnt_social_circle,days_last_phone_change,flag_document_2,flag_document_3,flag_document_4,flag_document_5,flag_document_6,flag_document_7,flag_document_8,flag_document_9,flag_document_10,flag_document_11,flag_document_12,flag_document_13,flag_document_14,flag_document_15,flag_document_16,flag_document_17,flag_document_18,flag_document_19,flag_document_20,flag_document_21,amt_req_credit_bureau_hour,amt_req_credit_bureau_day,amt_req_credit_bureau_week,amt_req_credit_bureau_mon,amt_req_credit_bureau_qrt,amt_req_credit_bureau_year,sk_id_prev_count,cnt_instalment_future_sum,sk_dpd_max,sk_dpd_sum,sk_dpd_def_max,sk_dpd_def_sum,sk_id_bureau_count,credit_day_overdue_sum,cnt_credit_prolong_avg,amt_credit_sum_sum,amt_credit_sum_debt_sum,amt_credit_sum_limit_sum,amt_credit_sum_overdue_sum,amt_annuity_sum,active_sum,amt_balance_avg_avg,amt_drawings_atm_current_avg_avg,amt_drawings_current_avg_avg,amt_drawings_other_current_avg_avg,amt_drawings_pos_current_avg_avg,amt_inst_min_regularity_avg_avg,amt_payment_current_avg_avg,amt_payment_total_current_avg_avg,amt_receivable_principal_avg_avg,amt_recivable_avg_avg,amt_total_receivable_avg_avg,cnt_drawings_atm_current_avg_avg,cnt_drawings_current_avg_avg,cnt_drawings_other_current_avg_avg,cnt_drawings_pos_current_avg_avg,cnt_instalment_mature_cum_avg_avg,sk_dpd_avg_avg,sk_dpd_def_avg_avg,negative_balance_avg_avg,negative_balance_sum_sum,count,installment_paiement_delay_min_min,installment_paiement_delay_max_max,installment_paiement_delay_avg_avg,amount_instalment_difference_min_min,amount_instalment_difference_max_max,amount_instalment_difference_avg_avg,prev_amt_annuity_sum,prev_amt_application_sum,prev_amt_credit_sum,prev_amt_down_payment_sum,prev_amt_goods_price_sum,prev_rate_down_payment_avg,prev_rate_interest_primary_avg,prev_rate_interest_privileged_avg,prev_days_decision_avg,prev_name_payment_type_count,prev_cnt_payment_sum,prev_days_first_drawing_avg,prev_days_first_due_avg,prev_days_last_due_1st_version_avg,prev_days_last_due_avg,prev_days_termination_avg,prev_nflag_insured_on_approval_avg
0,100599,0,Cash loans,False,True,0,315000.0,835380.0,40320.0,675000.0,"Spouse, partner",Commercial associate,Secondary / secondary special,House / apartment,0.032561,3820,8386.0,4028,NaN,1,1,0,1,0,0,Laborers,2.0,1,1,FRIDAY,12,0,0,0,0,0,0,Business Entity Type 1,NaN,0.682405,0.053478,0.0742,0.0581,0.9767,0.6804,0.0,0.0,0.2414,0.1667,0.2083,0.0601,0.0588,0.0667,0.0077,0.0061,0.0756,0.0603,0.9767,0.6929,0.0,0.0,0.2414,0.1667,0.2083,0.0615,0.0643,0.0694,0.0078,0.0065,0.0749,0.0581,0.9767,0.6847,0.0,0.0,0.2414,0.1667,0.2083,0.0612,0.0599,0.0679,0.0078,0.0062,reg oper account,block of flats,0.0535,Panel,False,0.0,0.0,0.0,0.0,-671.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,11.0,315.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,1415853.0,1244713.5,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-4.0,30.0,6.916667,0.0,31188.96,5571.645000,33429.870,630000.0,694863.0,NaN,630000.0,NaN,NaN,NaN,671.00,1.0,36.0,365243.0,-638.0,412.0,-368.000000,-362.000000,0.000000
1,165926,0,Cash loans,False,True,2,157500.0,163008.0,17424.0,144000.0,Unaccompanied,Commercial associate,Secondary / secondary special,With parents,0.006629,1304,4717.0,3486,NaN,1,1,0,1,0,0,Sales staff,4.0,2,2,THURSDAY,6,0,0,0,1,1,0,Self-employed,NaN,0.296449,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-2.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0,24.0,142.0,1.0,2.0,1.0,2.0,2.0,0.0,0.0,450738.0,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-10.0,33.0,7.624242,0.0,19414.89,1960.744500,75930.255,270000.0,1093959.0,NaN,270000.0,NaN,NaN,NaN,522.00,3.0,24.0,365243.0,-557.5,-227.5,-242.500000,-235.000000,1.000000
2,192297,0,Cash loans,False,True,0,157500.0,1006920.0,42790.5,900000.0,Unaccompanied,Pensioner,Lower secondary,House / apartment,0.018850,-365243,3924.0,2465,NaN,1,0,0,1,0,0,NaN,2.0,2,2,TUESDAY,10,0,0,0,0,0,0,XNA,0.459448,0.855000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,0.0,3.0,0.0,-508.0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,13.0,78.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,27.0,18.333333,0.0,0.00,0.000000,20975.040,206959.5,224716.5,0.0,206959.5,0.00000,NaN,NaN,508.00,1.0,12.0,365243.0,-476.0,-146.0,-146.000000,-142.000000,0.000000
3,127408,0,Cash loans,True,False,1,130500.0,835605.0,24561.0,697500.0,Unaccompanied,Working,Higher education,House / apartment,0.031329,275,3782.0,4349,64.0,1,1,0,1,0,0,Laborers,3.0,2,2,THURSDAY,7,0,0,0,0,1,1,Trade: type 7,0.483715,0.025700,0.382502,0.1031,NaN,0.9836,0.7756,NaN,0.0,0.2069,0.1667,0.2083,0.0415,NaN,0.0877,NaN,0.0070,0.1050,NaN,0.9836,0.7844,NaN,0.0,0.2069,0.1667,0.2083,0.0424,NaN,0.0914,NaN,0.0074,0.1041,NaN,0.9836,0.7786,NaN,0.0,0.2069,0.1667,0.2083,0.0422,NaN,0.0893,NaN,0.0071,reg oper account,block of flats,0.0706,Block,False,1.0,0.0,1.0,0.0,-207.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,13.0,68.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,135000.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-6.0,31.0,15.884615,0.0,3028.32,375.805385,31331.970,1019371.5,1017954.0,5400.0,1019371.5,0.05927,NaN,NaN,587.00,3.0,72.0,365243.0,-1510.0,-1180.0,-1210.000000,-1201.000000,0.000000
4,118673,0,Cash loans,False,True,0,202500.0,152820.0,16047.0,135000.0,Unaccompanied,Working,Secondary / secondary special,House / apartment,0.002506,2192,7013.0,1052,NaN,1,1,0,1,0,0,Laborers,2.0,2,2,MONDAY,8,0,0,0,0,1,1,Business Entity Type 3,NaN,0.236240,0.780144,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,0.0,0.0,0.0,0.0,-611.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0,16.0,77.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,238500.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,38.0,24.250000,0.0,0.00,0.000000,34127.955,223114.5,248283.0,0.0,223114.5,0.00000,NaN,NaN,284.75,4.0,24.0,365243.0,-301.0,-91.0,121564.666667,121567.333333,0.333333

In [13]:
# split 80% untuk train-test, 20% untuk validation
application_train_test_set, application_validation_set = train_test_split(applications, test_size=0.2, random_state=555)

# display results
display(application_train_test_set.shape, application_train_test_set.head(3), application_validation_set.shape, application_validation_set.head(3))

(24004, 178)

,id,credit_event,name_contract_type,flag_own_car,flag_own_realty,cnt_children,amt_income_total,amt_credit,amt_annuity,amt_goods_price,name_type_suite,name_income_type,name_education_type,name_housing_type,region_population_relative,days_employed,days_registration,days_id_publish,own_car_age,flag_mobil,flag_emp_phone,flag_work_phone,flag_cont_mobile,flag_phone,flag_email,occupation_type,cnt_fam_members,region_rating_client,region_rating_client_w_city,weekday_appr_process_start,hour_appr_process_start,reg_region_not_live_region,reg_region_not_work_region,live_region_not_work_region,reg_city_not_live_city,reg_city_not_work_city,live_city_not_work_city,organization_type,ext_source_1,ext_source_2,ext_source_3,apartments_avg,basementarea_avg,years_beginexpluatation_avg,years_build_avg,commonarea_avg,elevators_avg,entrances_avg,floorsmax_avg,floorsmin_avg,landarea_avg,livingapartments_avg,livingarea_avg,nonlivingapartments_avg,nonlivingarea_avg,apartments_mode,basementarea_mode,years_beginexpluatation_mode,years_build_mode,commonarea_mode,elevators_mode,entrances_mode,floorsmax_mode,floorsmin_mode,landarea_mode,livingapartments_mode,livingarea_mode,nonlivingapartments_mode,nonlivingarea_mode,apartments_medi,basementarea_medi,years_beginexpluatation_medi,years_build_medi,commonarea_medi,elevators_medi,entrances_medi,floorsmax_medi,floorsmin_medi,landarea_medi,livingapartments_medi,livingarea_medi,nonlivingapartments_medi,nonlivingarea_medi,fondkapremont_mode,housetype_mode,totalarea_mode,wallsmaterial_mode,emergencystate_mode,obs_30_cnt_social_circle,def_30_cnt_social_circle,obs_60_cnt_social_circle,def_60_cnt_social_circle,days_last_phone_change,flag_document_2,flag_document_3,flag_document_4,flag_document_5,flag_document_6,flag_document_7,flag_document_8,flag_document_9,flag_document_10,flag_document_11,flag_document_12,flag_document_13,flag_document_14,flag_document_15,flag_document_16,flag_document_17,flag_document_18,flag_document_19,flag_document_20,flag_document_21,amt_req_credit_bureau_hour,amt_req_credit_bureau_day,amt_req_credit_bureau_week,amt_req_credit_bureau_mon,amt_req_credit_bureau_qrt,amt_req_credit_bureau_year,sk_id_prev_count,cnt_instalment_future_sum,sk_dpd_max,sk_dpd_sum,sk_dpd_def_max,sk_dpd_def_sum,sk_id_bureau_count,credit_day_overdue_sum,cnt_credit_prolong_avg,amt_credit_sum_sum,amt_credit_sum_debt_sum,amt_credit_sum_limit_sum,amt_credit_sum_overdue_sum,amt_annuity_sum,active_sum,amt_balance_avg_avg,amt_drawings_atm_current_avg_avg,amt_drawings_current_avg_avg,amt_drawings_other_current_avg_avg,amt_drawings_pos_current_avg_avg,amt_inst_min_regularity_avg_avg,amt_payment_current_avg_avg,amt_payment_total_current_avg_avg,amt_receivable_principal_avg_avg,amt_recivable_avg_avg,amt_total_receivable_avg_avg,cnt_drawings_atm_current_avg_avg,cnt_drawings_current_avg_avg,cnt_drawings_other_current_avg_avg,cnt_drawings_pos_current_avg_avg,cnt_instalment_mature_cum_avg_avg,sk_dpd_avg_avg,sk_dpd_def_avg_avg,negative_balance_avg_avg,negative_balance_sum_sum,count,installment_paiement_delay_min_min,installment_paiement_delay_max_max,installment_paiement_delay_avg_avg,amount_instalment_difference_min_min,amount_instalment_difference_max_max,amount_instalment_difference_avg_avg,prev_amt_annuity_sum,prev_amt_application_sum,prev_amt_credit_sum,prev_amt_down_payment_sum,prev_amt_goods_price_sum,prev_rate_down_payment_avg,prev_rate_interest_primary_avg,prev_rate_interest_privileged_avg,prev_days_decision_avg,prev_name_payment_type_count,prev_cnt_payment_sum,prev_days_first_drawing_avg,prev_days_first_due_avg,prev_days_last_due_1st_version_avg,prev_days_last_due_avg,prev_days_termination_avg,prev_nflag_insured_on_approval_avg
26883,288213,0,Cash loans,False,False,0,225000.0,953460.0,62703.0,900000.0,Unaccompanied,Commercial associate,Secondary / secondary special,House / apartment,0.04622,116,4106.0,912,NaN,1,1,0,1,0,0,Realty agents,1.0,1,1,MONDAY,12,0,0,0,0,0,0,Services,0.702389,0.655313,NaN,0.0742,0.0503,0.9871,NaN,NaN,0.08,0.0690,0.3333,NaN,0.0103,NaN,0.0434,NaN,0.0,0.0756,0.0522,0.9871,NaN,NaN,0.0806,0.0690,0.3333,NaN,0.0105,NaN,0.0452,NaN,0.0,0.0749,0.0503,0.9871,NaN,NaN,0.08,0.0690,0.3333,NaN,0.0104,NaN,0.0441,NaN,0.0,NaN,block of flats,0.0578,Panel,False,2.0,0.0,2.0,0.0,-1698.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,2.0,0.0,14.0,42.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,69966.63,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0,28.0,18.583333,0.0,0.0,0.000000,64207.980,396441.0,352071.0,47470.5,396441.0,0.159215,NaN,NaN,933.666667,3.0,12.0,365243.0,-1326.000000,-1176.000000,-1176.000000,-1170.000000,0.000000
16448,400317,0,Cash loans,False,True,0,90000.0,284400.0,16011.0,225000.0,"Spouse, partner",Pensioner,Secondary / secondary special,House / apartment,0.00702,-365243,13237.0,3346,NaN,1,0,0,1,0,0,NaN,2.0,2,2,FRIDAY,9,0,0,0,0,0,0,XNA,NaN,0.507868,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,1.0,-1185.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0,96.0,863.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,0.000,NaN,NaN,0.000000,NaN,0.0000,0.000000,0.000000,0.000000,NaN,0.0000,NaN,NaN,0.000000,0.000000,0.000000,0.0,0.0,1.0,1.0,43.0,20.186012,0.0,0.0,0.000000,168705.135,2137072.5,2545960.5,11997.0,2137072.5,0.036304,NaN,NaN,1095.555556,9.0,118.0,365243.0,39646.888889,40013.555556,80502.333333,80507.222222,0.444444
8438,191384,0,Cash loans,False,True,0,180000.0,454500.0,15151.5,454500.0,Unaccompanied,Pensioner,Secondary / secondary special,House / apartment,0.04622,-365243,425.0,1622,NaN,1,0,0,1,1,0,NaN,1.0,1,1,WEDNESDAY,14,0,0,0,0,0,0,XNA,NaN,0.597959,0.4171,NaN,0.0769,0.9985,NaN,NaN,0.16,0.1379,0.3750,NaN,NaN,NaN,0.1852,NaN,NaN,NaN,0.0798,0.9985,NaN,NaN,0.1611,0.1379,0.3750,NaN,NaN,NaN,0.1930,NaN,NaN,NaN,0.0769,0.9985,NaN,NaN,0.16,0.1379,0.3750,NaN,NaN,NaN,0.1885,NaN,NaN,NaN,block of flats,0.1719,Panel,False,1.0,0.0,1.0,0.0,0.0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,1.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,2788155.00,1285911.0,0.0,0.0,NaN,0.0,70922.142656,4809.375,4809.375,0.0,0.0,4573.573579,7477.739063,7454.0625,67824.745781,70929.111094,70929.111094,0.3125,0.3125,0.0,0.0,38.936842,0.104167,0.104167,0.0,0.0,1.0,-10.0,30.0,6.843220,0.0,9000.0,52.436441,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

(6001, 178)

,id,credit_event,name_contract_type,flag_own_car,flag_own_realty,cnt_children,amt_income_total,amt_credit,amt_annuity,amt_goods_price,name_type_suite,name_income_type,name_education_type,name_housing_type,region_population_relative,days_employed,days_registration,days_id_publish,own_car_age,flag_mobil,flag_emp_phone,flag_work_phone,flag_cont_mobile,flag_phone,flag_email,occupation_type,cnt_fam_members,region_rating_client,region_rating_client_w_city,weekday_appr_process_start,hour_appr_process_start,reg_region_not_live_region,reg_region_not_work_region,live_region_not_work_region,reg_city_not_live_city,reg_city_not_work_city,live_city_not_work_city,organization_type,ext_source_1,ext_source_2,ext_source_3,apartments_avg,basementarea_avg,years_beginexpluatation_avg,years_build_avg,commonarea_avg,elevators_avg,entrances_avg,floorsmax_avg,floorsmin_avg,landarea_avg,livingapartments_avg,livingarea_avg,nonlivingapartments_avg,nonlivingarea_avg,apartments_mode,basementarea_mode,years_beginexpluatation_mode,years_build_mode,commonarea_mode,elevators_mode,entrances_mode,floorsmax_mode,floorsmin_mode,landarea_mode,livingapartments_mode,livingarea_mode,nonlivingapartments_mode,nonlivingarea_mode,apartments_medi,basementarea_medi,years_beginexpluatation_medi,years_build_medi,commonarea_medi,elevators_medi,entrances_medi,floorsmax_medi,floorsmin_medi,landarea_medi,livingapartments_medi,livingarea_medi,nonlivingapartments_medi,nonlivingarea_medi,fondkapremont_mode,housetype_mode,totalarea_mode,wallsmaterial_mode,emergencystate_mode,obs_30_cnt_social_circle,def_30_cnt_social_circle,obs_60_cnt_social_circle,def_60_cnt_social_circle,days_last_phone_change,flag_document_2,flag_document_3,flag_document_4,flag_document_5,flag_document_6,flag_document_7,flag_document_8,flag_document_9,flag_document_10,flag_document_11,flag_document_12,flag_document_13,flag_document_14,flag_document_15,flag_document_16,flag_document_17,flag_document_18,flag_document_19,flag_document_20,flag_document_21,amt_req_credit_bureau_hour,amt_req_credit_bureau_day,amt_req_credit_bureau_week,amt_req_credit_bureau_mon,amt_req_credit_bureau_qrt,amt_req_credit_bureau_year,sk_id_prev_count,cnt_instalment_future_sum,sk_dpd_max,sk_dpd_sum,sk_dpd_def_max,sk_dpd_def_sum,sk_id_bureau_count,credit_day_overdue_sum,cnt_credit_prolong_avg,amt_credit_sum_sum,amt_credit_sum_debt_sum,amt_credit_sum_limit_sum,amt_credit_sum_overdue_sum,amt_annuity_sum,active_sum,amt_balance_avg_avg,amt_drawings_atm_current_avg_avg,amt_drawings_current_avg_avg,amt_drawings_other_current_avg_avg,amt_drawings_pos_current_avg_avg,amt_inst_min_regularity_avg_avg,amt_payment_current_avg_avg,amt_payment_total_current_avg_avg,amt_receivable_principal_avg_avg,amt_recivable_avg_avg,amt_total_receivable_avg_avg,cnt_drawings_atm_current_avg_avg,cnt_drawings_current_avg_avg,cnt_drawings_other_current_avg_avg,cnt_drawings_pos_current_avg_avg,cnt_instalment_mature_cum_avg_avg,sk_dpd_avg_avg,sk_dpd_def_avg_avg,negative_balance_avg_avg,negative_balance_sum_sum,count,installment_paiement_delay_min_min,installment_paiement_delay_max_max,installment_paiement_delay_avg_avg,amount_instalment_difference_min_min,amount_instalment_difference_max_max,amount_instalment_difference_avg_avg,prev_amt_annuity_sum,prev_amt_application_sum,prev_amt_credit_sum,prev_amt_down_payment_sum,prev_amt_goods_price_sum,prev_rate_down_payment_avg,prev_rate_interest_primary_avg,prev_rate_interest_privileged_avg,prev_days_decision_avg,prev_name_payment_type_count,prev_cnt_payment_sum,prev_days_first_drawing_avg,prev_days_first_due_avg,prev_days_last_due_1st_version_avg,prev_days_last_due_avg,prev_days_termination_avg,prev_nflag_insured_on_approval_avg
24427,150203,0,Cash loans,False,False,3,112500.0,450000.0,17095.5,450000.0,"Spouse, partner",Working,Secondary / secondary special,House / apartment,0.022800,3567,10395.0,2156,NaN,1,1,0,1,0,0,Laborers,5.0,2,2,WEDNESDAY,7,0,0,0,0,1,1,Business Entity Type 3,0.192086,0.590017,0.612704,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,0.0,3.0,0.0,-1854.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,60.0,173.0,5.0,5.0,5.0,5.0,12.0,0.0,0.0,2714330.16,157612.5,0.00,0.0,91800.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-9.0,63.0,13.898661,0.0,0.00,0.000000,45529.740,313902.0,319999.5,21330.0,313902.0,0.075322,NaN,NaN,1899.666667,12.0,77.0,365243.0,-1942.125000,-1743.375,-1792.125,-1776.50,0.375000
12662,280239,0,Cash loans,True,True,0,135000.0,564124.5,36180.0,481500.0,Unaccompanied,Working,Secondary / secondary special,House / apartment,0.035792,1324,4507.0,4501,1.0,1,1,0,1,0,0,Cooking staff,2.0,2,2,TUESDAY,9,0,0,0,0,0,0,Business Entity Type 3,NaN,0.522996,0.553165,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,1.0,0.0,-1748.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0,51.0,458.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,372721.50,119169.0,0.00,0.0,22174.11,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,26.0,11.300379,0.0,0.00,0.000000,38878.155,626440.5,653845.5,0.0,626440.5,0.000000,NaN,NaN,647.666667,6.0,58.0,365243.0,-821.000000,-416.000,182141.250,182142.75,0.250000
20390,193539,0,Cash loans,False,False,0,153000.0,593010.0,19260.0,495000.0,Unaccompanied,Commercial associate,Secondary / secondary special,House / apartment,0.019101,2768,6487.0,4396,NaN,1,1,0,1,0,0,Medicine staff,1.0,2,2,WEDNESDAY,12,0,0,0,0,1,1,Medicine,0.366697,0.693460,0.096948,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-1709.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,2.0,0.0,52.0,394.0,18.0,53.0,0.0,0.0,15.0,0.0,0.0,3331486.80,1825240.5,14323.05,0.0,56715.12,0.0,37807.226203,1708.860759,1708.860759,0.0,0.0,2440.640769,2805.476013,2780.886076,35869.955696,37868.885316,37868.885316,0.088608,0.088608,0.0,0.0,34.730769,1.113924,0.620253,0.0,0.0,1.0,-43.0,31.0,7.386722,0.0,7589.16,528.830372,57778.110,894479.4,1128928.5,2025.9,894479.4,0.015726,NaN,NaN,1658.333333,9.0,124.0,303967.5,-2158.833333,59355.500,59335.500,59339.50,0.333333

In [14]:
# save datasets
application_train_test_set.to_csv("../datasets/raw/applications_train_test_set.csv", index=False)
application_validation_set.to_csv("../datasets/raw/applications_validation_set.csv", index=False)